plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.sega2028.menzomovil'
version = '1.0.0'

android {
  namespace "expo.modules.voiceforegroundservice"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.17.0"
}
